apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  ports:
  - port: 9980
    protocol: TCP
    targetPort: 8080
    nodePort: 30980
  selector:
    app: api-gateway
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: orionhank/bootu-apigateway:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "700Mi"
            cpu: "500m"
          limits:
            memory: "800Mi"
            cpu: "600m"
